sonar.projectKey=Pytest_Automation_Project
sonar.projectName=Pytest_Automation_Project
sonar.projectVersion=1.0

sonar.sources=.
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**/__pycache__/**,**/*.pyc,venv/**,.venv/**,.git/**
