[browser]
# Options: chrome | firefox
browser = firefox

# Options: normal | headless
mode = normal

[application]
url = https://ecommerce-playground.lambdatest.io/index.php?route=common/home
title = Your Store

[timeouts]
implicit_wait = 10
explicit_wait = 15
page_load_timeout = 30

[billing]
first_name = Sami
last_name = Test
company = CompanyX
address = Street 1
city = Chennai
postcode = 600001
country = India
region = Tamil Nadu

# ================= ADDED (NEW SECTION) =================
[product]
name = HP LP3065

[checkout]
payment_method = cod
shipping_method = flat